version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kenphotos-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kenphotos
      MYSQL_USER: kenphotos
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
